### ISSUE TITLE
Show existing window

### ISSUE THREAD

**Issue by Andreln** [FantasticFiasco/mvvm-dialogs-contrib#12]
Hello, I'm sorry this might be the wrong forum to ask this, but I've found no other suitable place.

I'm trying to use mvvm-dialogs to open a non-modal window used to display some application settings and if the settings window is already opened I want to show it instead of opening a new one. 

I know this is possible using the modal window, but I don't really want to halt code execution.

Is there a way to do this? I cant quite wrap my head around how I should proceed?

```
private void OpenSettings()
{
     var dialogViewModel = new SettingsViewModel();
     DialogService.Show<SettingsView>(this, dialogViewModel);
}
```

**Comment by FantasticFiasco** [comment]
So it would be an activation of a window if it already existed, or showing a new dialog if it didn't exist?

**Comment by Andreln** [comment]
Yes, thats a better way to explain it.

Den ons. 27. mar. 2019, 18:03 skrev Mattias Kindborg @FantasticFiasco <
notifications@github.com>:

**Comment by FantasticFiasco** [comment]
A compromise would be that you keep track of whether the window has been opened or not, by keeping a reference to the window view model (`viewModel`) specified when you opened it using `IDialogService.Show(ownerViewModel, viewModel)`.

If the window hasn't been opened, you create the view model and open the window. If you have opened the window and would like to activate it, you would have to call `IDialogService.Activate(viewModel)`. How does that sound. If `Activate` was implemented, would it solve you use case?

**Comment by Andreln** [comment]
Yeah, that would be perfect I think.

My first thought was to keep a reference of the viemodel, but I got stuck
on how to activate the window.

Den ons. 27. mar. 2019, 18:47 skrev Mattias Kindborg @FantasticFiasco <
notifications@github.com>:

**Comment by FantasticFiasco** [comment]
I've created a [branch in MvvmDialogs called  feat/activate-window](https://github.com/FantasticFiasco/mvvm-dialogs/tree/feat/activate-window) with a sample application called `Demo.ActivateNonModalDialog`. Please play around with it to verify that the feature behaves as you've requested.

**Comment by Andreln** [comment]
The sample works great. I use it like this:
```
private INotifyPropertyChanged dialogViewModel { get; } = new CurrentTimeDialogViewModel();

...

private void ImplicitShow()
{
    if (dialogService.Activate(dialogViewModel) == null)
    {
        dialogService.Show(this, dialogViewModel);
    }
}
```

Will this get into the nuget package?

Thank you for the help!

**Comment by FantasticFiasco** [comment]
I'd love to implement this, it seems like a really useful feature! Unfortunately I won't get the time to do it in one or two weeks.

Until then you can add the following code to your own project.

```
public static class Extensions
{
    public static bool? Activate(this IDialogService self, INotifyPropertyChanged viewModel)
    {
        foreach (Window window in Application.Current.Windows)
        {
            if (window.DataContext == viewModel)
            {
                return window.Activate();
            }
        }

        return null;
    }
}
```

It is basically the same code we had in `DialogService`, but you can have it in your code base, as a polyfill, until MvvmDialogs gets the feature. I've updated the sample project [with this code](https://github.com/FantasticFiasco/mvvm-dialogs/blob/feat/activate-window/samples/net/Demo.ActivateNonModalDialog/Extensions.cs) if you would like to check it out.

Would this solution work for you in the short term? If it does, and if you find [MvvmDialogs](https://github.com/FantasticFiasco/mvvm-dialogs) useful, don't forget to give it a star :)

**Comment by Andreln** [comment]
Awesome. No rush. This works perfectly for me.

Already starred it :) Thanks for the help. I really appreciate it.

Den tor. 28. mar. 2019, 22:10 skrev Mattias Kindborg @FantasticFiasco <
notifications@github.com>:

**Comment by FantasticFiasco** [comment]
No problems! You had a really good idea that will increase the value of this project, it is me who should thank you.

I'll keep you updated when the feature is officially released.

**Comment by FantasticFiasco** [comment]
There is now a [v5.3.0 release](https://www.nuget.org/packages/MvvmDialogs/5.3.0) available with the functionality to activate a non-modal dialog.

Thanks for the feedback!

**Comment by Andreln** [comment]
Awesome, thanks :)

Will update my projects asap.

-André

man. 29. apr. 2019, 20:51 skrev Mattias Kindborg @FantasticFiasco <
notifications@github.com>:
